DROP TYPE IF EXISTS categ_produse;
DROP TYPE IF EXISTS tipuri_produse;

CREATE TYPE categ_produse AS ENUM('gaming', 'business', 'home');
CREATE TYPE tipuri_produse AS ENUM('unitate centrala', 'laptop', 'mouse', 'tastatura', 'monitor', 'casti');


CREATE TABLE IF NOT EXISTS produse (
    id serial PRIMARY KEY,--a
    nume VARCHAR(50) UNIQUE NOT NULL,--b
    descriere TEXT,--c
    imagine VARCHAR(300),--d
    sursa_imagine VARCHAR(3000),
    categorie categ_produse DEFAULT 'home',--e
    tip_produs tipuri_produse,--f
    pret NUMERIC(8,2) NOT NULL,--g
    reducere NUMERIC(8,2),--h
    data_adaugare TIMESTAMP DEFAULT current_timestamp,--i
    producator VARCHAR(50),--j
    caracteristici VARCHAR [],--k
    returnare BOOLEAN NOT NULL DEFAULT FALSE --l
);

INSERT into produse (nume, descriere, imagine, sursa_imagine, categorie, tip_produs, pret, reducere, producator, caracteristici, returnare) VALUES
--gaming
--Luat de pe https://www.emag.ro/sistem-desktop-pc-gaming-lenovo-legion-t5-26amr5-cu-procesor-amd-ryzentm-5-5600g-pana-la-4-40ghz-16gb-ddr4-512gb-ssd-m-2-pcie-geforce-rtx-3060-12gb-gddr6-no-os-90rc00surm/pd/DK7HGPMBM/?X-Search-Id=325b06d040e82d8b8e3d&X-Product-Id=8644338&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view
('Lenovo Legion T5 26AMR5', 'Obtineti un gameplay revolutionar din cel mai avansat procesor din lume, cu performante impresionante, care va permit sa va deplasati mai repede, sa tintiti mai bine si sa aduceti tot ce este mai bun la fiecare lupta. Urmariti cum jocurile prind viata cu imagini captivante si receptivitate. Imbunatatiti jocul cu PC-uri alimentate de procesoare desktop AMD Ryzen ™ 5000 Series.', 'lenovo_legion_t5_26amr5.jpg', 'https://www.emag.ro/sistem-desktop-pc-gaming-lenovo-legion-t5-26amr5-cu-procesor-amd-ryzentm-5-5600g-pana-la-4-40ghz-16gb-ddr4-512gb-ssd-m-2-pcie-geforce-rtx-3060-12gb-gddr6-no-os-90rc00surm/pd/DK7HGPMBM/?X-Search-Id=325b06d040e82d8b8e3d&X-Product-Id=8644338&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'unitate centrala', '5599.99', '50', 'Lenovo', '{"Procesor: AMD Ryzen™ 5 5600G", "4.40GHz", "16GB DDR4", "512GB SSD M.2 PCIe", "GeForce RTX 3060 12GB GDDR6", "No OS"}', TRUE),
--Luat de pe https://www.emag.ro/laptop-gaming-lenovo-ideapad-3-15ach6-cu-procesor-amd-ryzen-5-5600h-pana-la-4-2ghz-15-6-full-hd-ips-8gb-512gb-ssd-nvidia-geforce-gtx-1650-4gb-no-os-shadow-black-82k2007brm/pd/D7YGGPMBM/?X-Search-Id=12ffa6d9f463692d0404&X-Product-Id=8647660&X-Search-Page=1&X-Search-Position=0&X-Section=search&X-MB=0&X-Search-Action=view
('Lenovo IdeaPad 3 15ACH6', 'Se spune ca nu puteti avea performante ridicate si o durata lunga de viata a bateriei pe acelasi laptop. Ei spun ca un laptop de jocuri performant trebuie sa fie mare, voluminos si greu. Au gresit. Acum va puteti bucura de jocuri de elita pe un laptop subtire si usor, cu o durata de viata uimitoare a bateriei, datorita noilor procesoare mobile AMD Ryzen ™ 5000 din seria H. Nu va mai compromiteti niciodata laptopul de jocuri.', 'lenovo_ideapad_3.jpg', 'https://www.emag.ro/laptop-gaming-lenovo-ideapad-3-15ach6-cu-procesor-amd-ryzen-5-5600h-pana-la-4-2ghz-15-6-full-hd-ips-8gb-512gb-ssd-nvidia-geforce-gtx-1650-4gb-no-os-shadow-black-82k2007brm/pd/D7YGGPMBM/?X-Search-Id=12ffa6d9f463692d0404&X-Product-Id=8647660&X-Search-Page=1&X-Search-Position=0&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'laptop', '3299.99', '50', 'Lenovo', '{"Procesor: AMD Ryzen 5 5600H", "4.2GHz", "Dimensiunea: 15.6", "Full HD", "IPS", "8GB", "512GB SSD", "NVIDIA GeForce GTX 1650 4GB", "No OS", "Shadow Black"}', TRUE),
--Luat de pe https://www.emag.ro/mouse-gaming-wireless-trust-gxt-107-izza-iluminare-rgb-negru-23214trust/pd/DR28HMMBM/?X-Search-Id=1e2785d54f6e98ee02cd&X-Product-Id=6496299&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view
('Trust GXT 107 Izza', 'In cautarea unui mouse de gaming convenabil, care sa acopere toate functionalitatile de baza, dar care sa aiba si un design wireless puternic? Cu factorul sau de forma ambidextra, 6 butoane responsive si design iluminat, GXT 107 Izza Mouse Gaming Wireless te va satisface.', 'lenovo_ideapad_3.jpg', 'https://www.emag.ro/mouse-gaming-wireless-trust-gxt-107-izza-iluminare-rgb-negru-23214trust/pd/DR28HMMBM/?X-Search-Id=1e2785d54f6e98ee02cd&X-Product-Id=6496299&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'mouse', '59.99', '0', 'Trust International B.V.', '{"Wireless", "Iluminare RGB", "Negru"}', FALSE),
--Luat de pe emag.ro/tastatura-gaming-mecanica-a-k75-iluminare-rainbow-tgsk75/pd/DBZZSTMBM/?X-Search-Id=1737ef55edff80bdf0f9&X-Product-Id=7854783&X-Search-Page=1&X-Search-Position=2&X-Section=search&X-MB=0&X-Search-Action=view
('A+ K75', 'Esti incepator sau pur si simplu hardware-ul iti diminueaza performanta? O intrebare la care doar experienta de gamer iti poate raspunde. De aceea alegerea tastaturii potrivite este o sarcina extrem de importanta, mai ales in cazul in care iti doresti atat performanta cat si distractie. Tastatura gaming mecanica A+ K75, iti confera precizie sporita si lejeritate in miscare datorita eficientei miscarii degetel in momentul tastarii.', 'a+_k75.webp', 'emag.ro/tastatura-gaming-mecanica-a-k75-iluminare-rainbow-tgsk75/pd/DBZZSTMBM/?X-Search-Id=1737ef55edff80bdf0f9&X-Product-Id=7854783&X-Search-Page=1&X-Search-Position=2&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'tastatura', '49.99', '0', 'A+', '{"Material: metal + ABS", "Comutator rosu, 50 milioane de clickuri", "Switch- blue", "Cablu 1.5M PU", "Tensiune de operare: USB 5V", "Forta de operare: 60g ± 10g", "Distanta totala: 4.0 ± 0.5mm", "Plug and play", "Dimensiuni: 355mm*135mm*20mm", "Greutate: 641g ± 20g", "Compatibil cu Windows XP, Vista, Win7, Win8, Win10A, Android, Linux, Max & Mac"}', FALSE),
--Luat de pe https://www.emag.ro/monitor-curbat-gaming-led-va-samsung-odyssey-27-full-hd-display-port-240hz-g-sync-dark-blue-gray-lc27rg50fqrxen/pd/DZV19TMBM/?X-Search-Id=c47fae0fe97388c24fb9&X-Product-Id=77170382&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view
('Samsung Odyssey 27', 'Lider in monitoare curbate, Samsung a condus piata monitoarelor curbate din momentul in care au introdus pentru prima data ecranele inovative in anul 2015. Cu o tehnologie de varf, monitoarele curbate Samsung sunt in permanenta numarul 1 pe piata si prima alegere a consumatorilor.', 'samsung_odyssey_27.webp', 'https://www.emag.ro/monitor-curbat-gaming-led-va-samsung-odyssey-27-full-hd-display-port-240hz-g-sync-dark-blue-gray-lc27rg50fqrxen/pd/DZV19TMBM/?X-Search-Id=c47fae0fe97388c24fb9&X-Product-Id=77170382&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'monitor', '1249.99', '49.99', 'Samsung', '{"Putere consumata:48 W", "Culoare: Negru", "Greutate: 4.6 Kg", "Lungime: 616.6 mm", "Latime: 250.5 mm", "Inaltime: 472.3 mm", "Tehnologie display: VA", "Tip rezolutie: Full HD", "Rezolutie optima: 1920 x 1080", "Tip iluminare fundal: LED", "Aspect imagine: 16:9", "Format ecran: Wide", "Tip suprafata display: Anti glare", "Luminozitate: 300 cd/m²", "Timp de raspuns: 4ms", "Unghi maxim vizibilitate orizontala/verticala: 178°/178°", "Contrast tipic: 3000:1", "Contrast dinamic: Mega DCR", "Rata de refresh (maximala): 240 Hz", "Numar culori: 16.7 M", "Porturi video: 2 x HDMI 1 x DisplayPort", "Porturi audio: 1 x Audio out", "Functii speciale: Ecran curbat Ergonomie Kensington Lock", "Montare pe perete: VESA 75 x 75 mm", "Tehnologii: Off Timer Plus Black Equalizer Flicker Free Eye Saver Mode NVIDIA® G-Sync™ Screen Size Optimizer Refresh Rate Optimizor Super Arena Gaming UX Easy Setting Box", "Continut pachet: 1 x cablu DisplayPort 1 x Cablu alimentare 1 x Manual de utilizare 1 x Monitor", "Inclinare: -2° +15°"}', TRUE),
--Luat de pe https://www.emag.ro/casti-gaming-cu-microfon-a-nuwa-cgk40/pd/DYKX5FBBM/?X-Search-Id=5b62d9db6e19c9df301b&X-Product-Id=4506423&X-Search-Page=1&X-Search-Position=2&X-Section=search&X-MB=0&X-Search-Action=view
('A+ Nuwa', 'Fie ca iti doresti sa faci un streaming de calitate, sa comunci cu playerii tai preferati sau sa iti imunatatesti experienta in joc, castile cu microfon CGK40 A+ te “aduc” mai aproape de el, imbunatatindu-ti experienta alaturi de un sunet clar, cald si fara distorsiuni sau lipsuri de frecvente deranjante, aducand cu sine o stare generala de buna dispozitie. Atent si armonios concepute, pentru a va oferi un sunet de calitate, castile pentru gaming A+ te vor incanta inca de la prima utilizare.', 'a+_nuwa.webp', 'https://www.emag.ro/casti-gaming-cu-microfon-a-nuwa-cgk40/pd/DYKX5FBBM/?X-Search-Id=5b62d9db6e19c9df301b&X-Product-Id=4506423&X-Search-Page=1&X-Search-Position=2&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'casti', '59.99', '0', 'A+', '{"Frecventa de raspuns (Hz): 20 - 20 000", "Conectare: Jack 3.5 mm", "Diametru difuzor (mm): 50", "Impedanta: 16 Ohm", "Microfon: Da", "Lungime cablu (m): 2.2"}', FALSE),
--Luat de pe https://www.emag.ro/casti-gaming-onikuma-k1-surround-sound-7-1-microfon-noise-cancelling-zero-ear-pressure-multi-platform-gri-svf036294-gy/pd/D05C0GBBM/?X-Search-Id=23f815e99b7dbdd187a9&X-Product-Id=55627556&X-Search-Page=1&X-Search-Position=4&X-Section=search&X-MB=0&X-Search-Action=view
('Onikuma K1', 'Microfon profesional de anulare a zgomotului, suport moale pentru furtunuri de burete. Excelent pentru a juca jocuri pe calculator. Designul pliabil reglabil din otel este puternic si durabil. Dimensiunea poate fi ajustata in functie de circumferinta capului. Greutate usoara si portabila, usor de transportat si de utilizat. O calitate buna a sunetului, va ofera o experienta muzicala buna. Performanta este stabila, iar calitatea sunetului telefonului care raspunde este foarte clara. Potrivit pentru activitati interioare si exterioare, usor de utilizat.', 'onikuma_k1.webp', 'https://www.emag.ro/casti-gaming-onikuma-k1-surround-sound-7-1-microfon-noise-cancelling-zero-ear-pressure-multi-platform-gri-svf036294-gy/pd/D05C0GBBM/?X-Search-Id=23f815e99b7dbdd187a9&X-Product-Id=55627556&X-Search-Page=1&X-Search-Position=4&X-Section=search&X-MB=0&X-Search-Action=view', 'gaming', 'casti', '99.99', '0', 'ONIKUMA', '{"Frecventa de raspuns (Hz): 20 Hz-20K Hz", "Conectare: Jack 3.5 mm", "Diametru difuzor (mm): 50 mm", "Impedanta: 20 Ω + 15%", "Microfon: Da", "Lungime cablu (m): 2.2 m", "Greutate: 380 g", "Altele: Control volum", "Compozitie: ABS, plastic"}', FALSE),

--business
--Luat de pe https://www.emag.ro/desktop-pc-intel-dual-core-g530-2-4-ghz-4-gb-ddr3-hdd-500-gb-g530-4gb-hdd500/pd/DB8TN6BBM/?X-Search-Id=47592e65046239957e58&X-Product-Id=47985069&X-Search-Page=1&X-Search-Position=0&X-Section=search&X-MB=0&X-Search-Action=view
('Intel Dual Core G530', 'Desktop PC Intel Dual Core G530 2,4 Ghz, 4 GB DDR3, HDD 500 GB', 'intel_dual_core_g530.webp', 'https://www.emag.ro/desktop-pc-intel-dual-core-g530-2-4-ghz-4-gb-ddr3-hdd-500-gb-g530-4gb-hdd500/pd/DB8TN6BBM/?X-Search-Id=47592e65046239957e58&X-Product-Id=47985069&X-Search-Page=1&X-Search-Position=0&X-Section=search&X-MB=0&X-Search-Action=view', 'business', 'unitate centrala', '599.99', '50', 'Spacer', '{"Procesor: Intel® Celeron G530 2.4 GHz", "RAM: DDR3, DDR3L 4GB", "500GB HDD SATA 7200 rpm", "Intel HD Graphics "}', TRUE),
--Luat de pe https://www.emag.ro/tastatura-logitech-k120-business-usb-layout-us-intl-negru-920-002509/pd/EJ952BBBM/?X-Search-Id=165160cbda71d08e4ef3&X-Product-Id=144600&X-Search-Page=1&X-Search-Position=0&X-Section=search&X-MB=0&X-Search-Action=view
('Logitech K120', 'Confortabila si eleganta, stil si simplitate, toate incluse in Logitech K120.', 'logitech_k120.webp', 'https://www.emag.ro/tastatura-logitech-k120-business-usb-layout-us-intl-negru-920-002509/pd/EJ952BBBM/?X-Search-Id=165160cbda71d08e4ef3&X-Product-Id=144600&X-Search-Page=1&X-Search-Position=0&X-Section=search&X-MB=0&X-Search-Action=view', 'business', 'tastatura', '59.99', '0', 'Logitech', '{"Interfata tastatura: USB", "Tehnologie: Cu fir", "Culoare: Negru", "Lungime cablu: 1.5m", "Rezistenta la apa", "Taste silentioase"}', FALSE),
--Luat de pe https://www.emag.ro/monitor-business-led-ips-asus-23-8-full-hd-frameless-fullhd-webcam-mic-array-flicker-free-low-blue-light-hdmi-be24eqk/pd/D975P2MBM/?X-Search-Id=89a47dfb049f4bbd32f4&X-Product-Id=66858312&X-Search-Page=1&X-Search-Position=3&X-Section=search&X-MB=0&X-Search-Action=view
('LED IPS ASUS 23.8', 'ASUS BE24EQK este un monitor Full HD de 23,8 inci care dispune de o camera web integrata Full HD (2MP), o gama de microfoane si boxe stereo pentru conferinte video si transmisie live. Cu rezolutie Full HD si un panou IPS fara rama pentru vizualizarea in unghi larg, ofera imagini incredibil de clare si redare video uimitoare. Compatibilitatea sa cu un suport standard VESA de 100 x 100 mm permite montarea pe perete sau instalarea flexibila pe un brat de afisare.', 'led_ips_asus_23.8.webp', 'https://www.emag.ro/monitor-business-led-ips-asus-23-8-full-hd-frameless-fullhd-webcam-mic-array-flicker-free-low-blue-light-hdmi-be24eqk/pd/D975P2MBM/?X-Search-Id=89a47dfb049f4bbd32f4&X-Product-Id=66858312&X-Search-Page=1&X-Search-Position=3&X-Section=search&X-MB=0&X-Search-Action=view', 'business', 'monitor', '1249.99', '49.99', 'Asus', '{"Diagonala: 23.8 inch", "Tehnologie display: LED IPS", "Tip rezolutie: Full HD", "Rezolutie optima: 1920 x 1080", "Tip iluminare fundal: LED", "Aspect imagine: 16:9", "Format ecran: Wide", "Tip suprafata display: Anti glare", "Luminozitate: 300 cd/mp", "Timp de raspuns: 	5 ms (GtG)", "Unghi maxim vizibilitate orizontala/verticala: 178°/178°", "Contrast tipic: 1000:1", "Contrast dinamic: 100000000:1", "Dimensiune punct: 0.275 mm", "Rata de refresh (maximala): 76 Hz", "Numar culori: 16.7 M", "Porturi video: 1 x HDMI 1 x D-sub 1 x DisplayPort", "Porturi audio: 1 x Audio out 1 x Audio in", "Data ports: 1 x USB"}', TRUE),
--Luat de pe https://www.emag.ro/casti-wireless-microsoft-modern-business-negru-8js-00011/pd/DSMK49MBM/?X-Search-Id=66a574d00151806f557d&X-Product-Id=8944304&X-Search-Page=1&X-Search-Position=20&X-Section=search&X-MB=0&X-Search-Action=view
('Casti wireless Microsoft Modern', 'Castile ofera sunet de inalta calitate, microfon cu capacitate de reducere a zgomotului, confort wireless, comenzi intuitive pentru apeluri Microsoft Teams in regim „maini libere” si multe altele.', 'casti_wireless_microsoft_modern.webp', 'https://www.emag.ro/casti-wireless-microsoft-modern-business-negru-8js-00011/pd/DSMK49MBM/?X-Search-Id=66a574d00151806f557d&X-Product-Id=8944304&X-Search-Page=1&X-Search-Position=20&X-Section=search&X-MB=0&X-Search-Action=view', 'business', 'casti', '599.99', '0', 'Microsoft', '{"Frecventa de raspuns (Hz): Frecventa microfon 100 Hz-10 kHz 100 Hz-20KHz", "Conectare: Bluetooth USB", "Diametru difuzor (mm): 28", "Microfon: Da", "Greutate: 136g"}', TRUE),

--home
--Luat de pe https://www.emag.ro/sistem-desktop-pc-dell-inspiron-3891-cu-procesor-intelr-coretm-i5-10400-pana-la-4-30-ghz-comet-lake-8gb-ddr4-512gb-ssd-intelr-uhd-graphics-630-windows-10-home-di3891i58512wh/pd/DSZDKXMBM/?X-Search-Id=0c6243ac3787bf7e078a&X-Product-Id=8706770&X-Search-Page=1&X-Search-Position=7&X-Section=search&X-MB=0&X-Search-Action=view
('Dell Inspiron 3891', 'Sistem Desktop PC Dell Inspiron 3891 cu procesor Intel® Core™ i5-10400 pana la 4.30 GHz, Comet Lake, 8GB DDR4, 512GB SSD, Intel® UHD Graphics 630, Windows 10 Home', 'dell_inspiron_3891.webp', 'https://www.emag.ro/sistem-desktop-pc-dell-inspiron-3891-cu-procesor-intelr-coretm-i5-10400-pana-la-4-30-ghz-comet-lake-8gb-ddr4-512gb-ssd-intelr-uhd-graphics-630-windows-10-home-di3891i58512wh/pd/DSZDKXMBM/?X-Search-Id=0c6243ac3787bf7e078a&X-Product-Id=8706770&X-Search-Page=1&X-Search-Position=7&X-Section=search&X-MB=0&X-Search-Action=view', 'home', 'unitate centrala', '2999.99', '50', 'Dell', '{"Sistem de operare: Microsoft Windows 10 Home", "Continut pachet: Mouse + Tastatura + 1 x Sistem PC", "Lungime: 154 mm", "Adancime: 293 mm", "Inaltime: 324.3 mm", "Greutate: 7.02 Kg", "Culoare: Negru", "Procesor: Intel® i5 10400", "RAM: DDR4 8GB", "Capacitate Stocare: SSD 512GB", "Placa video: Integrata Intel® UHD Graphics 630"}', TRUE),
--Luat de pe https://www.emag.ro/mouse-wireless-trust-mydo-silent-click-albastru-21870/pd/D1HHP9BBM/?X-Search-Id=c72a69fa453c621a1d79&X-Product-Id=91207241&X-Search-Page=1&X-Search-Position=3&X-Section=search&X-MB=0&X-Search-Action=view
('Trust Mydo silent click', 'Reduce sunetele cu cel putin 90%, Gama wireless de 10 m (2,4 GHz), Butonul pentru selectarea vitezei (1000/1400/1800 DPI), Receptor micro USB, Comutator pornire / oprire, Pentru utilizare in stanga si la dreapta', 'trust_mydo_silent_click.webp', 'https://www.emag.ro/mouse-wireless-trust-mydo-silent-click-albastru-21870/pd/D1HHP9BBM/?X-Search-Id=c72a69fa453c621a1d79&X-Product-Id=91207241&X-Search-Page=1&X-Search-Position=3&X-Section=search&X-MB=0&X-Search-Action=view', 'home', 'mouse', '39.99', '0', 'Trust', '{"Rezolutie (dpi): 1800", "Interfata mouse: Wireless", "Mouse mini: 3/1", "Tehnologie: Fara fir", "Senzor: Optic", "Interfata receiver: USB", "Culoare: Albastru", "Dimensiune (mm): 104 x 70 x 35 mm", "Greutate (g): 0.84"}', FALSE),
--Luat de pe https://www.emag.ro/monitor-lenovo-l22i-30-ips-21-5-full-hd-1920x1080-75-hz-4-ms-hdmi-vga-66cakac1eu/pd/DB82XPMBM/?X-Search-Id=e30ea82657c6c5203b0b&X-Product-Id=8573260&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view
('Lenovo L22i-30', 'Panoul de comutare in plan de 54,6 cm (21,5) al lui L22i-30 cu design pe 3 laturi aproape fara margini ofera imagini de calitate, precum si un aspect modern. L22i-30 a adoptat un suport metalic elegant cu suport pentru telefon si canal de gestionare a cablurilor. Utilizatorii se pot cufunda cu usurinta in divertisment cu o rata de reimprospatare de 75 Hz si sincronizare gratuita, in timp ce tehnologia de ingrijire a ochilor certificata Low Blue Light reduce oboseala ochilor chiar si dupa ore lungi. Cu software-ul Artery incarcat, utilizatorii pot ajusta setarile monitorului cu interfata convenabila.', 'lenovo_l22i-30.webp', 'https://www.emag.ro/monitor-lenovo-l22i-30-ips-21-5-full-hd-1920x1080-75-hz-4-ms-hdmi-vga-66cakac1eu/pd/DB82XPMBM/?X-Search-Id=e30ea82657c6c5203b0b&X-Product-Id=8573260&X-Search-Page=1&X-Search-Position=1&X-Section=search&X-MB=0&X-Search-Action=view', 'home', 'monitor', '699.99', '50', 'Lenovo', '{"Diagonala: 21.5 inch", "Tehnologie display	LED IPS", "Tip rezolutie: Full HD", "Rezolutie optima: 1920 x 1080", "Tip iluminare fundal: W-LED", "Aspect imagine: 16:9", "Format ecran: Wide", "Tip suprafata display: Anti glare", "Luminozitate: 250 cd/mp", "Timp de raspuns: 4 ms", "Unghi maxim vizibilitate orizontala/verticala: 178°/178°", "Contrast tipic: 1000:1", "Rata de refresh (maximala): 75 Hz", "Numar culori: 16.7 Milioane"}', TRUE),
--Luat de pe https://www.emag.ro/casti-profesionale-shure-design-circumaural-srh440-e/pd/DRPYW2BBM/?X-Search-Id=c135730e4d3dcc0fa8b2&X-Product-Id=16305758&X-Search-Page=1&X-Search-Position=23&X-Section=search&X-MB=0&X-Search-Action=view
('Shure SRH440-E', 'Castile Shure SRH440-E ofera un raspuns excelent in intreg spectrul audio cat si o izolare remarcabila datorita tehnologiei “closed-back” . Designul calitativ cat si greutatea redusa ofera un plus de confort la utilizarea de lunga durata. Se preteaza foarte bine la monitorizarea inregistrarilor in studio cat si pentru home entertainment.', 'shure_srh440-e.webp', 'https://www.emag.ro/casti-profesionale-shure-design-circumaural-srh440-e/pd/DRPYW2BBM/?X-Search-Id=c135730e4d3dcc0fa8b2&X-Product-Id=16305758&X-Search-Page=1&X-Search-Position=23&X-Section=search&X-MB=0&X-Search-Action=view', 'home', 'casti', '499.99', '0', 'Shure', '{"Conectori: Jack 3.5", "Culoare: Negru", "Impedanta iesire: 44 Ω", "Raspuns in frecventa: 10 - 22000", "Lungime cablu: 300 cm", "Diametru difuzor: 40 mm", "Greutate: 311 g"}', TRUE)
